#! /bin/sh
# ASCII art splash screen to be loaded after .profile

art_dir="${XDG_CONFIG_HOME}/ascii_splash"

if [ -d $art_dir ]; then
  splash_exec="$art_dir/splash.sh"
  if [ -x "$splash_exec" ]; then
    $splash_exec
  fi
fi

# vim:ft=sh
